import { NextResponse } from 'next/server';
import { agentGraph } from '../../../ai/agent/graph';

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { applicantName, appliedPosition, cvText, messages } = body;

    if (!applicantName || !appliedPosition || !cvText || !messages) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    // Invoke the LangGraph agent
    const initialState = {
      applicantName,
      appliedPosition,
      cvText,
      chatHistory: messages,
      // If we already have retrieved context from a previous turn, we should ideally pass it.
      // But for simplicity in a stateless HTTP route, LangGraph will re-retrieve it if empty.
      retrievedContext: body.retrievedContext || "",
      status: 'starting' as const,
    };

    const finalState = await agentGraph.invoke(initialState);

    // Get the last message generated by the agent
    const lastMessage = finalState.chatHistory[finalState.chatHistory.length - 1];

    return NextResponse.json({
      message: lastMessage,
      status: finalState.status,
      decision: finalState.decision,
      reasoning: finalState.reasoning,
      retrievedContext: finalState.retrievedContext, // send back so frontend can hold it
    });

  } catch (error: any) {
    console.error("Agent Interview Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
